// <auto-generated />
namespace AdsVenture.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class PublisherActiveCreatedOnUpdatedOn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PublisherActiveCreatedOnUpdatedOn));
        
        string IMigrationMetadata.Id
        {
            get { return "201407230338020_Publisher-Active-CreatedOn-UpdatedOn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
