//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataTables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataTables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DataTables", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : activate to sort column ascending.
        /// </summary>
        internal static string Aria_SortAscending {
            get {
                return ResourceManager.GetString("Aria_SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : activate to sort column descending.
        /// </summary>
        internal static string Aria_SortDescending {
            get {
                return ResourceManager.GetString("Aria_SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available in table.
        /// </summary>
        internal static string EmptyTable {
            get {
                return ResourceManager.GetString("EmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _START_ to _END_ from _TOTAL_ results.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 entries.
        /// </summary>
        internal static string InfoEmpty {
            get {
                return ResourceManager.GetString("InfoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (filtered from _MAX_ total entries).
        /// </summary>
        internal static string InfoFiltered {
            get {
                return ResourceManager.GetString("InfoFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string InfoThousands {
            get {
                return ResourceManager.GetString("InfoThousands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _MENU_ Results per page.
        /// </summary>
        internal static string LengthMenu {
            get {
                return ResourceManager.GetString("LengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string LoadingRecords {
            get {
                return ResourceManager.GetString("LoadingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string Paginate_First {
            get {
                return ResourceManager.GetString("Paginate_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string Paginate_Last {
            get {
                return ResourceManager.GetString("Paginate_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;rsaquo;.
        /// </summary>
        internal static string Paginate_Next {
            get {
                return ResourceManager.GetString("Paginate_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lsaquo;.
        /// </summary>
        internal static string Paginate_Previous {
            get {
                return ResourceManager.GetString("Paginate_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching records found.
        /// </summary>
        internal static string ZeroRecords {
            get {
                return ResourceManager.GetString("ZeroRecords", resourceCulture);
            }
        }
    }
}
